.TH "geoc-vector-shear" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector shear
.SH DESCRIPTION
Shear Features in a Layer
.SH USAGE
geoc vector shear -i points.properties -o points_sheared.shp -x 5 -y 10
.SH OPTIONS
-x --x-distance: The x distance
.PP
-y --y-distance: The y distance
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
