.TH "geoc-geometry-convert" "1" "5 December 2014" "version 0.1"
.SH NAME
geoc geometry convert
.SH DESCRIPTION
Convert a geometry from one format to another
.SH USAGE
geoc geometry convert -i "POINT (-122 48)" -f geojson
.SH OPTIONS
-i --input: The input geometry
.PP
-f --format: The output format
.PP
-p --format-options: The output format options
.PP
-t --type: The output type (geometry, feature, layer)
.PP
--help : Print the help message
.PP
