.TH "geoc-raster-reclassify" "1" "22 December 2014" "version 0.1"
.SH NAME
geoc raster reclassify
.SH DESCRIPTION
Reclassify a Raster
.SH USAGE
geoc raster reclassify -i raster.tif -o raster_reclass.tif -r 49-100=1 -r 100-256=255
.SH OPTIONS
-b --band: The band
.PP
-n --nodata: The NODATA value
.PP
-r --range: A range: from-to=value or 1-10=5
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
