.TH "geoc-raster-stylize" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc raster stylize
.SH DESCRIPTION
Create a new Raster by baking the style into an existing Raster
.SH OPTIONS
-s --style: The SLD style file
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
