.TH "geoc-raster-abs" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc raster abs
.SH DESCRIPTION
Calculate the absolute value for each cell.
.SH USAGE
geoc raster abs -i raster.tif -o raster_abs.tif
.SH OPTIONS
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
