.TH "geoc-tile-pyramid" "1" "11 May 2015" "version 0.1"
.SH NAME
geoc tile pyramid
.SH DESCRIPTION
Get a Pyramid from a TileLayer
.SH USAGE
geoc tile pyramid -l src/test/resources/earthquakes.mbtiles -n earthquakes
.SH OPTIONS
-l --tile-layer: The tile layer
.PP
-n --tile-layer-name: The tile layer name
.PP
-t --type: The type of tile layer(png, utfgrid, mvt, pbf)
.PP
-p --pyramid: The pyramid
.PP
-o --output-type: The output type (text, xml, json)
.PP
--help : Print the help message
.PP
