.TH "geoc-raster-animatedgif" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc raster animatedgif
.SH DESCRIPTION
Create an animated GIF from a list of GIFs.
.SH USAGE
geoc raster animatedgif -f image1.gif -f image2.gif -f image2.gif -o animated.gif -d 450 -r
.SH OPTIONS
-f --file: The GIF file
.PP
-o --output-file: The output animated GIF file
.PP
-d --delay: The delay between images
.PP
-r --repeat: Whether to repeat the animation or not
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
