.TH "geoc-vector-uniquevaluesstyle" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector uniquevaluesstyle
.SH DESCRIPTION
Create an SLD document where each unique value in the Layer is a rule.
.SH USAGE
geoc vector uniquevaluesstyle -i states.shp -f STATE_ABBR -c "Greens"
.SH OPTIONS
-f --field: The field name
.PP
-c --colors: The color brewer palette name or a list of colors (space delimited)
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
