.TH "geoc-raster-style-default" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc raster style default
.SH DESCRIPTION
Create a simple Raster SLD
.SH USAGE
geoc raster style default
.SH OPTIONS
-o --opacity: The opacity
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
