.TH "geoc-tile-get-bounds" "1" "18 September 2016" "version 0.1"
.SH NAME
geoc tile get bounds
.SH DESCRIPTION
Get the Bounds of a tile
.SH USAGE
geoc tile get bounds -p mercator -z 10 -x 245 -y 310
.SH OPTIONS
-p --pyramid: The tile pyramid
.PP
-z --zoom-level: The tile zoom level
.PP
-x --column: The tile x or column
.PP
-y --row: The tile y or row
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
