.TH "geoc-tile-delete" "1" "20 July 2015" "version 0.1"
.SH NAME
geoc tile delete
.SH DESCRIPTION
Delete tiles from a tile layer
.SH USAGE
geoc tile delete -l earthquakes.mbtiles -n earthquakes -z 2
.SH OPTIONS
-l --tile-layer: The tile layer
.PP
-n --tile-layer-name: The tile layer name
.PP
-t --type: The type of tile layer(png, utfgrid, mvt, pbf)
.PP
-p --pyramid: The pyramid
.PP
-i --tile: The Tile Z/X/Y coordinates
.PP
-b --bounds: The bounds
.PP
-z --zoom-level: The tile zoom level
.PP
-x --minx: The min x or col
.PP
-y --miny: The min y or row
.PP
-c --maxx: The max x or col
.PP
-u --maxy: The max y or row
.PP
--help : Print the help message
.PP
