.TH "geoc-raster-envelope" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc raster envelope
.SH DESCRIPTION
Get the Envelope of a Raster as a Vector Layer
.SH OPTIONS
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
