.TH "geoc-vector-addfields" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector addfields
.SH DESCRIPTION
Add one or more Fields to the input Layer to create the output Layer
.SH OPTIONS
-f --field: A Field in the format 'name=type'
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
