.TH "geoc-vector-update" "1" "18 December 2014" "version 0.1"
.SH NAME
geoc vector update
.SH DESCRIPTION
Update one Layer with another Layer
.SH USAGE
geoc vector update -i states.shp -k clip_layer.shp -o states_update.shp
.SH OPTIONS
-k --other-workspace: The other workspace
.PP
-y --other-layer: The other layer
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
