.TH "geoc-vector-count" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector count
.SH DESCRIPTION
Count the features, geometries, or points in a Layer
.SH USAGE
geoc vector count -i states.shp
.SH OPTIONS
-t --type: Count features, geometries, or points
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
