.TH "geoc-vector-buffer" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector buffer
.SH DESCRIPTION
Buffer the features of the input Layer and save them to the output Layer
.SH USAGE
geoc vector randompoints -n 10 -g "1,1,10,10" | geoc vector buffer -d 10
.SH OPTIONS
-d --distance: The buffer distance
.PP
-q --quadrantsegments: The number of quadrant segments
.PP
-s --singlesided: Whether buffer should be single sided or not
.PP
-c --capstyle: The cap style
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
