.TH "geoc-vector-graticule-line" "1" "13 December 2015" "version 0.1"
.SH NAME
geoc vector graticule line
.SH DESCRIPTION
Create line graticules
.SH USAGE
geoc vector graticule line -g -180,-90,180,90 -l "vertical,2,10" -l "vertical,1,2" -l "horizontal,2,10" -l "horizontal,1,2"
.SH OPTIONS
-g --geometry: The geometry
.PP
-s --spacing: The spacing (defaults to -1)
.PP
-l --line-definition: Each line definition has comma delimited orientation (vertical or horizontal), level, and spacing)
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
--help : Print the help message
.PP
