.TH "geoc-vector-ellipse" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc vector ellipse
.SH DESCRIPTION
Create a ellipse shape around each feature of the input Layer
.SH OPTIONS
-g --geometry: The geometry expression
.PP
-w --width: The width of the bounds
.PP
-h --height: The height of the bounds
.PP
-p --num-points: The number of points
.PP
-a --rotation: The angle of rotation
.PP
-u --unit: The unit can either be degrees(d) or radians(r). The default is degrees.
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
