.TH "geoc-vector-add" "1" "12 December 2014" "version 0.1"
.SH NAME
geoc vector add
.SH DESCRIPTION
Add a Feature to an existing Layer
.SH USAGE
geoc vector add -i mypoints.shp -v "id=1" -v "the_geom=POINT(1 1)" -v "name=House"
.SH OPTIONS
-v --value: A value 'field=value'
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
