.TH "geoc-geometry-plot" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc geometry plot
.SH DESCRIPTION
Draw a geometry to a plot
.SH OPTIONS
-i --input: The input geometry
.PP
-f --file: The output file
.PP
-w --width: The image width
.PP
-h --height: The image height
.PP
-l --legend: Whether to show the legend
.PP
-r --fill-coords: Whether to fill coordinates
.PP
-p --fill-polys: Whether to fill polygons
.PP
-d --draw-coords: Whether to draw coordinates
.PP
--help : Print the help message
.PP
