.TH "geoc-vector-largestemptycircle" "1" "29 August 2020" "version 0.1"
.SH NAME
geoc vector largestemptycircle
.SH DESCRIPTION
find the largest empty circle amound the features of the input Layer
.SH USAGE
geoc vector largestemptycircle -i points.shp -o circle.shp -t 1.0
.SH OPTIONS
-t --tolerance: The tolerance
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
