.TH "geoc-geometry-geohash-decode" "1" "24 May 2015" "version 0.1"
.SH NAME
geoc geometry geohash decode
.SH DESCRIPTION
Decode a GeoHash to a Geometry.
.SH USAGE
geoc geometry geohash decode -i uf8vk6wjr
.SH OPTIONS
-i --input: The input geohash
.PP
-t --type: Whether the geohash is a point or bounds
.PP
--help : Print the help message
.PP
