.TH "geoc-tile-pyramid" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc tile pyramid
.SH DESCRIPTION
Get a Pyramid from a TileLayer
.SH USAGE
geoc tile pyramid -l src/test/resources/earthquakes.mbtiles
.SH OPTIONS
-l --tile-layer: The tile layer
.PP
-o --output-type: The output type (text, xml, json)
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
