.TH "geoc-vector-to" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector to
.SH DESCRIPTION
Write a Layer to a String format (CSV, GeoJSON, KML, GML)
.SH OPTIONS
-f --format: The string format (CSV, GeoJSON, KML, GML)
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
