.TH "geoc-raster-point" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc raster point
.SH DESCRIPTION
Convert a Raster to a Point Vector Layer
.SH OPTIONS
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-raster: The input raster
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
