.TH "geoc-raster-style-channel-selection" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc raster style channel selection
.SH DESCRIPTION
Create a channel selection Raster SLD
.SH USAGE
geoc raster style channel selection -r "red,histogram,0.5" -g "green,normalize,0.25" -b "green,histogram,0.33"
.SH OPTIONS
-r --red: The red channel name
.PP
-g --green: The green channel name
.PP
-b --blue: The blue channel name
.PP
-y --gray: The gray channel name
.PP
-o --opacity: The opacity
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
