.TH "geoc-vector-database-index-create" "1" "15 December 2014" "version 0.1"
.SH NAME
geoc vector database index create
.SH DESCRIPTION
Create a database index
.SH USAGE
geoc vector database index create -w points.db-i geom_index -l points50 -f the_geom
.SH OPTIONS
-w --database-workspace: The input workspace
.PP
-l --layer-name: The input workspace
.PP
-i --index-name: The input workspace
.PP
-f --field: The input workspace
.PP
-u --unique: The input workspace
.PP
--help : Print the help message
.PP
