.TH "geoc-geometry-geohash-neighbors" "1" "11 June 2015" "version 0.1"
.SH NAME
geoc geometry geohash neighbors
.SH DESCRIPTION
Get a geohash's neighbors
.SH USAGE
geoc geometry geohash neighbors -i uf8vk6wjr
.SH OPTIONS
-i --input: The input geometry
.PP
-n --number-of-chars: The number of characters. The default is 9.
.PP
-d --bit-depth: The bit depth. The default is 52.
.PP
--help : Print the help message
.PP
