.TH "geoc-raster-scale" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc raster scale
.SH DESCRIPTION
Scale a Raster
.SH OPTIONS
-x --x-scale: The scale factor along the x axis
.PP
-y --y-scale: The scale factor along the y axis
.PP
-t --x-translate: The x translation
.PP
-r --y-translate: The y translation
.PP
-l --interpolation: The interpolation method (bicubic, bicubic2, bilinear, nearest)
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
