.TH "geoc-vector-interiorpoint" "1" "9 December 2014" "version 0.1"
.SH NAME
geoc vector interiorpoint
.SH DESCRIPTION
Get the interior point of each feature in the input Layer and save them to the output Layer
.SH USAGE
geoc vector interiorpoint -i states.shp -o state_interiorpoints.shp
.SH OPTIONS
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
