.TH "geoc-vector-graticule-oval" "1" "14 November 2019" "version 0.1"
.SH NAME
geoc vector graticule oval
.SH DESCRIPTION
Create oval graticules
.SH USAGE
geoc vector graticule oval -l 10 -g -180,-90,180,90
.SH OPTIONS
-g --geometry: The geometry
.PP
-l --length: The length
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
