.TH "geoc-raster-style-channel-selection" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc raster style channel selection
.SH DESCRIPTION
Create a channel selection Raster SLD
.SH OPTIONS
-r --red: The red channel name
.PP
-g --green: The green channel name
.PP
-b --blue: The blue channel name
.PP
-y --gray: The gray channel name
.PP
-o --opacity: The opacity
.PP
--help : Print the help message
.PP
