.TH "geoc-vector-validity" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc vector validity
.SH DESCRIPTION
Check whether geometry in a Layer is valid or not
.SH OPTIONS
-f --field: A Field to include when reporting an invalid Geometry
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
