.TH "geoc-vector-append" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector append
.SH DESCRIPTION
Append the Features from an other Layer to the input Layer
.SH OPTIONS
-k --other-workspace: The other workspace
.PP
-y --other-layer: The other layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
