.TH "geoc-vector-page" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector page
.SH DESCRIPTION
Page through Feature in the input Layer
.SH USAGE
cat states.csv | geoc vector page -t 0 -m 2
.SH OPTIONS
-m --max: The maximum number of Features to include
.PP
-t --start: The index of the Feature to start at
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
