.TH "geoc-raster-point" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc raster point
.SH DESCRIPTION
Convert a Raster to a Point Vector Layer
.SH USAGE
geoc raster point -i raster.tif -o points.shp
.SH OPTIONS
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
