.TH "geoc-raster-contour" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc raster contour
.SH DESCRIPTION
Create contours from a Raster
.SH OPTIONS
-b --band: The band
.PP
-l --level: A level or interval
.PP
-s --simplify: Whether to simplify
.PP
-m --smooth: Whether to smooth
.PP
-n --bounds: The bounds
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-raster: The input raster
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
