.TH "geoc-orthodromicdistance" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc orthodromicdistance
.SH DESCRIPTION
Calculate the orthodromic distance between two points.
.SH OPTIONS
-e --ellipsoid: The ellipsoid
.PP
-p --point1: The first point
.PP
-t --point2: The second point
.PP
--help : Print the help message
.PP
