.TH "geoc-vector-dissolveintersecting" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector dissolveintersecting
.SH DESCRIPTION
Dissolve the intersecting Features of a Layer.
.SH OPTIONS
-d --id-field: The id field name
.PP
-c --count-field: The count field name
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
