.TH "geoc-raster-crop-with-layer" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc raster crop with layer
.SH DESCRIPTION
Crop a Raster using the geometry from a Layer
.SH USAGE
geoc raster crop with layer -i alki.tif -o alki_cropped.tif -w poly.shp
.SH OPTIONS
-w --input-workspace: The input workspace
.PP
-y --input-layer: The input layer
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
