.TH "geoc-raster-exp" "1" "21 June 2015" "version 0.1"
.SH NAME
geoc raster exp
.SH DESCRIPTION
Calculate the exponent for each cell.
.SH USAGE
geoc raster exp -i raster.tif -o raster_exp.tif
.SH OPTIONS
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
