.TH "geoc-vector-defaultstyle" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector defaultstyle
.SH DESCRIPTION
Get the default style for the Layer
.SH USAGE
geoc vector defaultstyle zones.shp
.SH OPTIONS
-g --geometry-type: The geometry type
.PP
-c --color: The base color
.PP
-o --opacity: The opacity (defaults to 1.0)
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
