.TH "geoc-raster-style-shadedrelief" "1" "22 December 2014" "version 0.1"
.SH NAME
geoc raster style shadedrelief
.SH DESCRIPTION
Create a shaded relief Raster SLD
.SH USAGE
geoc raster style shadedrelief -r 65 -b -o 0.85
.SH OPTIONS
-b --brightness-only: The brightness only flag
.PP
-r --relief-factor: The relief factor
.PP
-o --opacity: The opacity
.PP
--help : Print the help message
.PP
