.TH "geoc-raster-resample" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc raster resample
.SH DESCRIPTION
Resample a Raster
.SH USAGE
geoc raster resample -i alki.tif -s "200,400" -o alki_resized.tif
.SH OPTIONS
-b --bounds: The bounding box
.PP
-s --size: The output size
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
