.TH "geoc-vector-from" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc vector from
.SH DESCRIPTION
Create a Layer from a string of KML, CSV, GML, or GeoJSON
.SH OPTIONS
-t --text: The text
.PP
-f --format: The string format (CSV, GeoJSON, KML, GML)
.PP
-g --geometry-type: The geometry type
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
--help : Print the help message
.PP
