.TH "geoc-raster-crop-with-geometry" "1" "22 December 2014" "version 0.1"
.SH NAME
geoc raster crop with geometry
.SH DESCRIPTION
Crop a Raster with a Geometry
.SH USAGE
geoc raster crop with geometry -i alki.gif -o alki_cropped.tif -g "`geom buffer -g "POINT (1166476.232632274 823276.6023305996)" -d 50`"
.SH OPTIONS
-g --geometry: The Geometry
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
