.TH "geoc-style-repository-save" "1" "19 October 2021" "version 0.1"
.SH NAME
geoc style repository save
.SH DESCRIPTION
Save a style to a style repository
.SH OPTIONS
-t --type: The type of style repository (directory, nested-directory, h2, sqlite, postgres)
.PP
-o --options: The style repository options
.PP
-l --layer-name: The layer name
.PP
-s --style-name: The style name
.PP
-f --style-file: The style file (sld or css)
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
