.TH "geoc-raster-to" "1" "22 December 2014" "version 0.1"
.SH NAME
geoc raster to
.SH DESCRIPTION
Convert a Raster from one format to another
.SH USAGE
geoc raster to -i raster.tif -o raster.png -f worldimage
.SH OPTIONS
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
