.TH "geoc-vector-subset" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector subset
.SH DESCRIPTION
Extract a subset of Features from the input Layer
.SH OPTIONS
-f --filter: The CQL Filter
.PP
-s --sort: The sort field
.PP
-m --max: The maximum number of Features to include
.PP
-t --start: The index of the Feature to start at
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
