.TH "geoc-style-repository-get" "1" "19 October 2021" "version 0.1"
.SH NAME
geoc style repository get
.SH DESCRIPTION
Get a styles from a style repository
.SH USAGE
"geoc style repository get -t h2 -p file=styles.db -l states -s states_population -f states_pop.sld"
.SH OPTIONS
-t --type: The type of style repository (directory, nested-directory, h2, sqlite, postgres)
.PP
-o --options: The style repository options
.PP
-l --layer-name: The layer name
.PP
-s --style-name: The style name
.PP
-f --output-file: The output file
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
