.TH "geoc-raster-mosaic" "1" "2 March 2019" "version 0.1"
.SH NAME
geoc raster mosaic
.SH DESCRIPTION
Mosaic a list of rasters together
.SH USAGE
geoc raster mosaic -r raster1.tif -r raster2.tif -o raster.tif
.SH OPTIONS
-r --raster: An input Raster
.PP
-b --bounds: The bounds
.PP
-z --size: The size
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
