.TH "geoc-vector-pointsalongline" "1" "16 June 2019" "version 0.1"
.SH NAME
geoc vector pointsalongline
.SH DESCRIPTION
Create points along lines
.SH USAGE
geoc vector pointsalongline -i rivers.shp -o sample_locations.shp -d 10.0
.SH OPTIONS
-d --distance: The distance between points
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
