.TH "geoc-vector-draw" "1" "7 January 2015" "version 0.1"
.SH NAME
geoc vector draw
.SH DESCRIPTION
Draw a Layer to an Image, PDF, or SVG Document
.SH USAGE
geoc vector draw -i states.shp -f image.png -w 600 -h 400 && open image.png
.SH OPTIONS
-f --file: The output file
.PP
-t --type: The type of document
.PP
-w --width: The width
.PP
-h --height: The height
.PP
-s --sld-file: The sld file
.PP
-b --bounds: The bounds
.PP
-m --base-map: The base map (can be a OSM tile set like stamen-toner, stamen-toner-lite, stamen-watercolor, mapquest-street, mapquest-satellite, shapefile, or Groovy script that returns Layers)
.PP
-g --background-color: The background color
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
