.TH "geoc-raster-crop" "1" "22 December 2014" "version 0.1"
.SH NAME
geoc raster crop
.SH DESCRIPTION
Crop a Raster
.SH USAGE
geoc raster crop -i raster.tif -b "-120,-40,120,40" -o raster_croped.tif
.SH OPTIONS
-b --bound: The Bounds
.PP
-x --pixel: Whether the Bounds is pixel or geographic
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
