.TH "geoc-vector-scale" "1" "20 December 2014" "version 0.1"
.SH NAME
geoc vector scale
.SH DESCRIPTION
Scale Feature in a Layer
.SH USAGE
geoc vector scale -i polys.properties -o scaled_polys.shp -x 5 -y 5 -c "getX(centroid(geom))" -d "getY(centroid(geom))"
.SH OPTIONS
-x --x-distance: The x distance
.PP
-y --y-distance: The y distance
.PP
-c --x-coord: The x coordinate
.PP
-d --y-coord: The y coordinate
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
