.TH "geoc-style-uniquevaluesfromtext" "1" "18 July 2021" "version 0.1"
.SH NAME
geoc style uniquevaluesfromtext
.SH DESCRIPTION
Create a Style from reading values in the unique values format
.SH USAGE
geoc style uniquevaluesfromtext -f unit -g Polygon -i units.txt -o units.sld
.SH OPTIONS
-f --field: The field
.PP
-g --geometry-type: The geometry type (point, linestring, polygon)
.PP
-i --input: The input file or url
.PP
-t --type: The output type (sld or ysld)
.PP
-o --output: The output file
.PP
-w --writer-options: The StyleWriter options
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
