.TH "geoc-raster-get-value" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc raster get value
.SH DESCRIPTION
Get the cell value from a Raster
.SH OPTIONS
-x --x-coordinate: The x coordinate
.PP
-y --y-coordinate: The y coordinate
.PP
-t --type: The type can be point or pixel
.PP
-b --band: The band to get a value from
.PP
-i --input-raster: The input raster
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
