.TH "geoc-raster-worldfile" "1" "22 December 2014" "version 0.1"
.SH NAME
geoc raster worldfile
.SH DESCRIPTION
Create a Raster world file
.SH USAGE
geoc raster worldfile -b 0,0,10,10 -s 5,5 -f test.pgw
.SH OPTIONS
-b --bounds: The bounds
.PP
-s --size: The size
.PP
-f --file: The world file
.PP
--help : Print the help message
.PP
