.TH "geoc-vector-removefields" "1" "12 December 2014" "version 0.1"
.SH NAME
geoc vector removefields
.SH DESCRIPTION
Remove one or more Fields from the input Layer to create the output Layer
.SH USAGE
geoc vector removefields -i states.shp -o states_temp.shp -f description -f name -f boundedBy
.SH OPTIONS
-f --field: A Field name
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
