.TH "geoc-vector-rotate" "1" "23 Dec 2013" "version 0.1"
.SH NAME
geoc vector rotate
.SH DESCRIPTION
Rotate Features in a Layer. Valid combinations of options include:
theta
theta, x, y
sine, cosine
sine, cosine, x, y
.SH OPTIONS
-t --theta: The angle of rotation in radians
.PP
-s --sine: The sine of the angle of rotation in radians
.PP
-c --cosine: The cosine of the angle of rotation in radians
.PP
-x --x-coord: The x coordinate of the rotation point
.PP
-y --y-coord: The x coordinate of the rotation point
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
