.TH "geoc-tile-generate" "1" "23 April 2015" "version 0.1"
.SH NAME
geoc tile generate
.SH DESCRIPTION
Generate tiles
.SH USAGE
geoc tile generate -l earthquakes.mbtiles -n earthquakes -m layerFile -s 0 -e 2 -v false
.SH OPTIONS
-l --tile-layer: The tile layer
.PP
-n --tile-layer-name: The tile layer name
.PP
-t --type: The type of tile layer(png, utfgrid, mvt, pbf)
.PP
-p --pyramid: The pyramid
.PP
-f --field: A field
.PP
-d --layer-fields: A List of sub fields for a layer
.PP
-m --base-map: The base map
.PP
-s --start-zoom: The start zoom level
.PP
-e --end-zoom: The end zoom level
.PP
-b --bounds: The bounds
.PP
-v --verbose: The verbose flag
.PP
--help : Print the help message
.PP
