.TH "geoc-vector-defaultstyle" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector defaultstyle
.SH DESCRIPTION
Get the default style for the Layer
.SH OPTIONS
-c --color: The base color
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
