.TH "geoc-vector-list-layers" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector list layers
.SH DESCRIPTION
List Layers in a DataStore
.SH USAGE
geoc vector list layers -i "dbtype=postgis database=naturalearth host=localhost port=5432 user=uzer password=s3cr3t"
.SH OPTIONS
-i --input-workspace: The input workspace
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
