.TH "geoc-proj-wkt" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc proj wkt
.SH DESCRIPTION
Get the WKT of a Projection
.SH USAGE
geoc proj wkt -e EPSG:4326
.SH OPTIONS
-e --epsg: The EPSG Projection code
.PP
-f --file: The output File
.PP
-c --citation: The citations (epsg or esri)
.PP
-i --indentation: The number of spaces to indent
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
