.TH "geoc-vector-remove-layer" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector remove layer
.SH DESCRIPTION
Remove a Layer from a Workspace
.SH USAGE
geoc vector remove layer -i layers.gpkg -l points
.SH OPTIONS
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
