.TH "geoc-raster-polygon" "1" "22 December 2014" "version 0.1"
.SH NAME
geoc raster polygon
.SH DESCRIPTION
Convert a Raster to a Polygon Vector Layer
.SH USAGE
geoc raster polygon -i raster.tif -o polygons.shp
.SH OPTIONS
-b --band: The band
.PP
-e --inside-edges: Whether to include inside edges
.PP
-g --region-of-interest: The region of interest
.PP
-n --no-data: A no data value
.PP
-a --range: A range (min,minIncluded,max,maxIncluded)
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
