.TH "geoc-vector-clip" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc vector clip
.SH DESCRIPTION
Clip the input Layer by the other Layer to produce the output Layer.
.SH OPTIONS
-k --other-workspace: The other workspace
.PP
-y --other-layer: The other layer
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
