.TH "geoc-raster-shadedrelief" "1" "30 September 2018" "version 0.1"
.SH NAME
geoc raster shadedrelief
.SH DESCRIPTION
Create a shaded relief raster
.SH USAGE
geoc raster shadedrelief -i elev.tif -o shadedrelief -s 1.0 -a 45.0 -m 15.0
.SH OPTIONS
-s --scale: The scale
.PP
-a --altitude: The altitude
.PP
-m --azimuth: The azimuth
.PP
-x --resx: The x resolution
.PP
-y --resy: The y resolution
.PP
-z --zeta-factory: The zeta factory
.PP
-g --algorithm: The algorithm
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
