.TH "geoc-geometry-geohash-bounds" "1" "11 June 2015" "version 0.1"
.SH NAME
geoc geometry geohash bounds
.SH DESCRIPTION
Calculate the geohashes for the given bounds
.SH USAGE
geoc geometry geohash bounds -b "120, 30, 120.0001, 30.0001"
.SH OPTIONS
-b --bounds: The input geometry
.PP
-t --type: The encoding type (string or long). The default is string.
.PP
-n --number-of-chars: The number of characters. The default is 9.
.PP
-d --bit-depth: The bit depth. The default is 52.
.PP
--help : Print the help message
.PP
