.TH "geoc-tile-list-tiles" "1" "18 September 2016" "version 0.1"
.SH NAME
geoc tile list tiles
.SH DESCRIPTION
Get a list of tiles for a given geometry
.SH USAGE
geoc tile list tiles -p mercator -z 10 -b "-13731759.2574,5981350.3374,-13512843.6084,6095547.2576"
.SH OPTIONS
-p --pyramid: The tile pyramid
.PP
-b --bounds: The bounds
.PP
-z --zoom-level: The tile zoom level
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
