.TH "geoc-vector-create" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc vector create
.SH DESCRIPTION
Create a new Layer
.SH OPTIONS
-f --field: A Field in the format 'name=type'
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
--help : Print the help message
.PP
