.TH "geoc-vector-database-index-list" "1" "20 December 2014" "version 0.1"
.SH NAME
geoc vector database index list
.SH DESCRIPTION
List database indices
.SH USAGE
geoc vector database index list -w points.db -l points50 -p
.SH OPTIONS
-w --database-workspace: The input workspace
.PP
-l --layer-name: The input workspace
.PP
-p --pretty-print: Whether to pretty print the output
.PP
--help : Print the help message
.PP
