.TH "geoc-vector-reflect" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector reflect
.SH DESCRIPTION
Reflect Features in a Layer
.SH USAGE
geoc vector reflect -i polys.properties -o reflected_polys.shp -x 5 -y 5
.SH OPTIONS
-x --x1-distance: The x1 distance
.PP
-y --y1-distance: The y1 distance
.PP
-c --x2-distance: The x2 distance
.PP
-d --y2-distance: The y2 distance
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
