.TH "geoc-raster-project" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc raster project
.SH DESCRIPTION
Project a Raster
.SH USAGE
geoc raster project -i raster.tif -o raster_4326.tif -t EPSG:4326
.SH OPTIONS
-t --target-projection: The target projection
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
