.TH "geoc-raster-size" "1" "31 May 2017" "version 0.1"
.SH NAME
geoc raster size
.SH DESCRIPTION
Get the Raster size (width,height)
.SH USAGE
geoc raster size -i raster.tif
.SH OPTIONS
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
