.TH "geoc-vector-draw" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector draw
.SH DESCRIPTION
Draw a Layer to an Image, PDF, or SVG Document
.SH OPTIONS
-f --file: The output file
.PP
-t --type: The type of document
.PP
-w --width: The width
.PP
-h --height: The height
.PP
-s --sld-file: The sld file
.PP
-b --bounds: The bounds
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
