.TH "geoc-vector-compareschemas" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector compareschemas
.SH DESCRIPTION
Compare Schemas from two Layers
.SH USAGE
geoc vector compareschemas -i states.shp -k states_xy.shp
.SH OPTIONS
-k --other-workspace: The other workspace
.PP
-y --other-layer: The other layer
.PP
-p --pretty-print: Whether to pretty print the output
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
