.TH "geoc-vector-translate" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector translate
.SH DESCRIPTION
Translate or move Feature in a Layer
.SH OPTIONS
-x --x-distance: The x distance
.PP
-y --y-distance: The y distance
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
