.TH "geoc-raster-style-contrast-enhancement" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc raster style contrast enhancement
.SH DESCRIPTION
Create a contrast enhancement Raster SLD
.SH OPTIONS
-m --method: The method (normalize or histogram)
.PP
-g --gamma-value: The gamma value
.PP
-o --opacity: The opacity
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
