.TH "geoc-geometry-geohash-encode" "1" "20 May 2015" "version 0.1"
.SH NAME
geoc geometry geohash encode
.SH DESCRIPTION
Encode a Geometry as a GeoHash
.SH USAGE
geoc jericks$ geoc geometry geohash encode -i "POINT (45 78)"
.SH OPTIONS
-i --input: The input geometry
.PP
-t --type: The encoding type (string or long). The default is string.
.PP
-n --number-of-chars: The number of characters. The default is 9.
.PP
-d --bit-depth: The bit depth. The default is 52.
.PP
--help : Print the help message
.PP
