.TH "geoc-geometry-greatcirclearc" "1" "1 December 2016" "version 0.1"
.SH NAME
geoc geometry greatcirclearc
.SH DESCRIPTION
Create a great circle arc.
.SH USAGE
geoc geometry greatcirclearc -p "POINT (-122 48)" -t "POINT (-77 39)"
.SH OPTIONS
-e --ellipsoid: The ellipsoid
.PP
-p --start-point: The start point
.PP
-t --end-point: The end point
.PP
-n --num-points: The number of points
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
