.TH "geoc-vector-raster-values" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc vector raster values
.SH DESCRIPTION
Get value from a Raster for each Feature's geometry
.SH OPTIONS
-n --field-name: The new value field name (defaults to value)
.PP
-t --field-type: The new value field type (defaults to double)
.PP
-b --band: The band to get values from (defaults to 0)
.PP
-s --input-raster: The input raster
.PP
-p --input-projection: The input projection
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
