.TH "geoc-style-css2sld" "1" "18 July 2021" "version 0.1"
.SH NAME
geoc style css2sld
.SH DESCRIPTION
Convert CSS to SLD
.SH USAGE
geoc style css2sld -i states.css -o states.sld
.SH OPTIONS
-i --input: The input file or url
.PP
-o --output: The output file
.PP
-w --writer-options: The StyleWriter options
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
