.TH "geoc-map-cube" "1" "18 May 2015" "version 0.1"
.SH NAME
geoc map cube
.SH DESCRIPTION
Create a map cube
.SH USAGE
geoc map cube -m map.groovy -f mapcube.png
.SH OPTIONS
-m --map: The groovy map file that contains the layers to render
.PP
-f --file: The output image file
.PP
-t --draw-tabs: The flag to whether to draw tabs or not
.PP
-s --tab-size: The tab size
.PP
--help : Print the help message
.PP
