.TH "geoc-vector-barnessurface" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector barnessurface
.SH DESCRIPTION
Create a barnes surface of the features from the input layer
.SH USAGE
geoc vector barnessurface -i point_grid.properties -o barnes.tif -s 1 -v value -m 1 -w 800 -h 800
.SH OPTIONS
-v --value-field: The name of the value field
.PP
-d --data-limit: The maximum number of features to process
.PP
-s --scale: The interpolation length
.PP
-c --convergence: The refinement factor
.PP
-p --passes: The number of passes
.PP
-m --min-observations: The minimum number of observations to be a grid cell
.PP
-x --max-observation-distance: The max distance for an observation to be a grid cell
.PP
-n --no-data: The no data value
.PP
-e --pixels-per-cell: The resolution of the computed grid
.PP
-q --query-buffer: The query buffer
.PP
-b --bounds: The output bounds
.PP
-w --width: The output width
.PP
-h --height: The output height
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
