.TH "geoc-vector-fix" "1" "2 October 2021" "version 0.1"
.SH NAME
geoc vector fix
.SH DESCRIPTION
Fix the geometry of the features of the input Layer and save them to the output Layer
.SH USAGE
"geoc vector fix -i lines.shp -o fixed_lines.shp"
.SH OPTIONS
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
