.TH "geoc-vector-display" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector display
.SH DESCRIPTION
Display a Layer in a simple viewer
.SH USAGE
geoc vector display -i points.shp -w 400 -h 400
.SH OPTIONS
-w --width: The width
.PP
-h --height: The height
.PP
-s --sld-file: The sld file
.PP
-b --bounds: The bounds
.PP
-m --layer: The map layer
.PP
-g --background-color: The background color
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
