.TH "geoc-carto-map" "1" "7 March 2022" "version 0.1"
.SH NAME
geoc carto map
.SH DESCRIPTION
Create a cartographic map
.SH USAGE
"geoc carto map -t json -c map.json -o map.png"
.SH OPTIONS
-t --type: The type of the carto file (json, xml)
.PP
-c --carto-file: The input carto definition file
.PP
-o --output-file: The output file
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
