.TH "geoc-vector-dump-shapefiles" "1" "4 December 2015" "version 0.1"
.SH NAME
geoc vector dump shapefiles
.SH DESCRIPTION
Create shapefiles from the input Layer
.SH USAGE
cat pointsAndPolygons.csv | geoc vector dump shapfiles -o shapefiles
.SH OPTIONS
-o --output-directory: The output directory
.PP
-s --max-shp-size: The maximum shp size
.PP
-d --max-dbf-size: The maximum dbf size
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
