.TH "geoc-vector-grid" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector grid
.SH DESCRIPTION
Create a vector grid
.SH OPTIONS
-y --rows: The number of rows
.PP
-x --columns: The number of columns
.PP
-w --cell-width: The cell width
.PP
-h --cell-height: The cell height
.PP
-t --type: The grid cell type
.PP
-g --geometry: The geometry
.PP
-p --projection: The projection
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
--help : Print the help message
.PP
