.TH "geoc-raster-crop-with-layer" "1" "12 October 2013" "version 0.1"
.SH NAME
geoc raster crop with layer
.SH DESCRIPTION
Crop a Raster with a Layer
.SH OPTIONS
-w ----input-workspace: The input workspace
.PP
-l ----input-layer: The input layer
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
