.TH "geoc-vector-raster" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc vector raster
.SH DESCRIPTION
Convert a vector Layer to a Raster
.SH OPTIONS
-d --field: The field name with value
.PP
-s --grid-size: The grid size
.PP
-b --bounds: The bounds
.PP
-n --raster-name: The raster name
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
--help : Print the help message
.PP
