.TH "geoc-vector-sort" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector sort
.SH DESCRIPTION
Sort the Features in the input Layer.
.SH USAGE
cat states.csv | geoc vector sort -s "STATE_NAME ASC"
.SH OPTIONS
-s --sort: The sort field
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
