.TH "geoc-vector-addidfield" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector addidfield
.SH DESCRIPTION
Add an ID Field
.SH USAGE
geoc vector addidfield -i states.shp -o states_id.shp -f ID -s 1
.SH OPTIONS
-f --id-fieldname: The name for the ID Field
.PP
-s --start: The number of start at
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
