.TH "geoc-raster-draw" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc raster draw
.SH DESCRIPTION
Draw a Raster to an image
.SH USAGE
geoc raster draw -i raster.tif -f map.png
.SH OPTIONS
-f --file: The output file
.PP
-t --type: The type of document
.PP
-w --width: The width
.PP
-h --height: The height
.PP
-s --sld-file: The sld file
.PP
-b --bounds: The bounds
.PP
-m --layer: The map layer
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
