.TH "geoc-vector-points2lines" "1" "26 September 2015" "version 0.1"
.SH NAME
geoc vector points2lines
.SH DESCRIPTION
Convert points to lines
.SH USAGE
geoc vector points2lines -i points.shp -o lines.shp -s id -g group
.SH OPTIONS
-s --sort-field: The Field to sort the field
.PP
-g --group-field: The Field used create separate Lines
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
