.TH "geoc-vector-addlengthfield" "1" "14 December 2014" "version 0.1"
.SH NAME
geoc vector addlengthfield
.SH DESCRIPTION
Add an length/perimeter Field
.SH USAGE
geoc vector addlengthfield -i roads.shp -o roads_len.shp -f LENGTH
.SH OPTIONS
-f --length-fieldname: The name for the length Field
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
