.TH "geoc-style-create" "1" "18 July 2021" "version 0.1"
.SH NAME
geoc style create
.SH DESCRIPTION
Create a simple style
.SH USAGE
geoc style create -s fill=white -s stroke=black -s stroke-width=0.1 -t ysld
.SH OPTIONS
-s --style-options: A style options
.PP
-t --type: The output type (sld or ysld)
.PP
-w --writer-options: The StyleWriter options
.PP
-o --output: The output file
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
