.TH "geoc-tile-generate" "1" "12 August 2015" "version 0.1"
.SH NAME
geoc tile generate
.SH DESCRIPTION
Generate tiles
.SH USAGE
geoc tile generate -l earthquakes.mbtiles -m layerFile -s 0 -e 2 -v false
.SH OPTIONS
-l --tile-layer: The tile layer
.PP
-f --field: A field
.PP
-d --layer-fields: A List of sub fields for a layer
.PP
-m --base-map: The base map
.PP
-s --start-zoom: The start zoom level
.PP
-e --end-zoom: The end zoom level
.PP
-b --bounds: The bounds
.PP
-i --missing: Whether to generate only missing tiles
.PP
-v --verbose: The verbose flag
.PP
--help : Print the help message
.PP
