.TH "geoc-style-repository-delete" "1" "19 October 2021" "version 0.1"
.SH NAME
geoc style repository delete
.SH DESCRIPTION
Delete a style to a style repository
.SH USAGE
"geoc style repository delete -t sqlite -p file=styles.db -l states -s states_population"
.SH OPTIONS
-t --type: The type of style repository (directory, nested-directory, h2, sqlite, postgres)
.PP
-o --options: The style repository options
.PP
-l --layer-name: The layer name
.PP
-s --style-name: The style name
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
