.TH "geoc-vector-database-select" "1" "20 December 2014" "version 0.1"
.SH NAME
geoc vector database select
.SH DESCRIPTION
Get a Layer from a Database using a SELECT statement
.SH USAGE
geoc vector database select -w h2.db -l centroids -o centroids.properties -s "SELECT ST_CENTROID("the_geom") as "the_geom", "id" FROM "polygons"" -g the_geom|Point
.SH OPTIONS
-w --database-workspace: The input workspace
.PP
-l --layer-name: The input layer
.PP
-s --sql: The input layer
.PP
-g --geometry-field: The geometry field (name|type|projection)
.PP
-p --primary-key-field: The primary key field names
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
--help : Print the help message
.PP
