.TH "geoc-vector-delete" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector delete
.SH DESCRIPTION
Delete features from a Layer in place
.SH USAGE
geoc vector delete -i states.shp -f "STATE_NAME = 'Washington'" -i states_no_wash.shp
.SH OPTIONS
-f --filter: The CQL Filter
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
