.TH "geoc-raster-projection" "1" "7 June 2017" "version 0.1"
.SH NAME
geoc raster projection
.SH DESCRIPTION
Get the Raster Projection
.SH USAGE
geoc raster projection -i raster.tif -t epsg
.SH OPTIONS
-t --type: The output type (epsg, id, srs, wkt)
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
