.TH "geoc-vector-pointstacker" "1" "18 December 2014" "version 0.1"
.SH NAME
geoc vector pointstacker
.SH DESCRIPTION
Group nearby points together
.SH USAGE
geoc vector poinstacker -i earthquakes.shp -o stacked_quakes.shp -c 5 -w 800 -h 600
.SH OPTIONS
-c --cell-size: The cell size in pixels which aggregates points
.PP
-b --bounds: The bounds
.PP
-w --width: The output width
.PP
-h --height: The output height
.PP
-s --source-projection: The source projection
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
