.TH "geoc-geometry-convert" "1" "16 December 2013" "version 0.1"
.SH NAME
geoc geometry convert
.SH DESCRIPTION
Convert a Geometry from one format to another.
.SH OPTIONS
-i --input: The input geometry
.PP
-f --format: The output format (kml, geojson, gml)
.PP
-p --format-options: The output format options (key=value)
.PP
-t --type: The output type (geometry, feature, layer)
.PP
--help : Print the help message
.PP
