.TH "geoc-vector-from" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector from
.SH DESCRIPTION
Create a Layer from a string of KML, CSV, GML, GEORSS, GEOBUF, GPX or GeoJSON
.SH USAGE
curl -s http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson | geoc vector from -f geojson
.SH OPTIONS
-t --text: The text
.PP
-f --format: The string format (CSV, GeoJSON, KML, GML)
.PP
-g --geometry-type: The geometry type
.PP
-p --format-options: A format options 'key=value'
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
