.TH "geoc-vector-schema" "1" "10 December 2014" "version 0.1"
.SH NAME
geoc vector schema
.SH DESCRIPTION
Get the Layer's schema
.SH USAGE
geoc vector schema -i states.shp -p
.SH OPTIONS
-p --pretty-print: Whether to pretty print the output
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
