.TH "geoc-vector-addxyfields" "1" "14 December 2014" "version 0.1"
.SH NAME
geoc vector addxyfields
.SH DESCRIPTION
Add a XY Fields
.SH USAGE
geoc vector addxyfields -i points.shp -o points_xy.shp -x X_COL -y Y_COL
.SH OPTIONS
-x --x-fieldname: The name for the X Field
.PP
-y --y-fieldname: The name for the Y Field
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
