.TH "geoc-vector-create" "1" "12 December 2014" "version 0.1"
.SH NAME
geoc vector create
.SH DESCRIPTION
Create a new Layer
.SH USAGE
geoc vector create -o mypoints.shp -f "the_geom=POINT EPSG:4326" -f "id=int" -f "name=string"
.SH OPTIONS
-f --field: A Field in the format 'name=type'
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
--help : Print the help message
.PP
