.TH "geoc-vector-mincircles" "1" "9 December 2014" "version 0.1"
.SH NAME
geoc vector mincircles
.SH DESCRIPTION
Calculate the minimum bounding circles of each feature in the input Layer and save them to the output Layer
.SH USAGE
geoc vector mincircles -i states.shp -o state_mincircles.shp
.SH OPTIONS
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
