.TH "geoc-geometry-orthodromicdistance" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc geometry orthodromicdistance
.SH DESCRIPTION
Calculate the orthodromic distance between two points.
.SH USAGE
geoc geometry orthodromicdistance -e wgs84 -p "-86.67 36.12" -t "-118.40 33.94"
.SH OPTIONS
-e --ellipsoid: The ellipsoid
.PP
-p --start-point: The start point
.PP
-t --end-point: The end point
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
