.TH "geoc-filter-cql2xml" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc filter cql2xml
.SH DESCRIPTION
Convert a CQL statement to an OCG XML Filter
.SH USAGE
geoc filter cql2xml -c STATE_ABBR=WA
.SH OPTIONS
-c --cql: The CQL statement
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
