.TH "geoc-style-ysld2sld" "1" "18 July 2021" "version 0.1"
.SH NAME
geoc style ysld2sld
.SH DESCRIPTION
Convert YSLD to SLD
.SH USAGE
geoc style ysld2sld -i countries.yml -o countries.sld
.SH OPTIONS
-i --input: The input file or url
.PP
-o --output: The output file
.PP
-w --writer-options: The StyleWriter options
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
