.TH "geoc-vector-filter" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc vector filter
.SH DESCRIPTION
Filter features from the input Layer and save them to the output Layer
.SH OPTIONS
-f --filter: The CQL Filter
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
