.TH "geoc-style-sld2ysld" "1" "23 April 2016" "version 0.1"
.SH NAME
geoc style sld2ysld
.SH DESCRIPTION
Convert SLD to YSLD
.SH USAGE
geoc style sld2ysld -i countries.sld -o countries.yml
.SH OPTIONS
-i --input: The input file or url
.PP
-o --output: The output file
.PP
--help : Print the help message
.PP
