.TH "geoc-raster-info" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc raster info
.SH DESCRIPTION
Get information about a Raster
.SH OPTIONS
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
