.TH "geoc-raster-add-constant" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc raster add constant
.SH DESCRIPTION
Add a constant value to a Raster
.SH USAGE
geoc raster add constant -i raster.tif -v 100 -o raster_add_100.tif
.SH OPTIONS
-v --value: The value
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
