.TH "geoc-geometry-pt2dd" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc geometry pt2dd
.SH DESCRIPTION
Format a Point in Decimal Degrees
.SH USAGE
geoc geometry pt2dd -p "POINT (-122.5256194 47.212022222)" -t dms
.SH OPTIONS
-p --point: The Point
.PP
-t --type: The output type (dms, dms_char, ddm, ddm_char)
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
