.TH "geoc-vector-rotate" "1" "20 December 2014" "version 0.1"
.SH NAME
geoc vector rotate
.SH DESCRIPTION
Rotate Features in a Layer
.SH USAGE
geoc vector rotate -i polys.properties -o rotated_polys.shp -t 0.785 -x "getX(centroid(geom))" -y "getY(centroid(geom))"
.SH OPTIONS
-t --theta: The angle of rotation in radians
.PP
-s --sine: The sine of the angle of rotation in radians
.PP
-c --cosine: The cosine of the angle of rotation in radians
.PP
-x --x-coord: The x coordinate of the rotation point
.PP
-y --y-coord: The y coordinate of the rotation point
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
