.TH "geoc-style-repository-list" "1" "19 October 2021" "version 0.1"
.SH NAME
geoc style repository list
.SH DESCRIPTION
List styles from a style repository
.SH OPTIONS
-t --type: The type of style repository (directory, nested-directory, h2, sqlite, postgres)
.PP
-o --options: The style repository options
.PP
-l --layer-name: The layer name
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
