.TH "geoc-vector-snap-points2lines" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector snap points2lines
.SH DESCRIPTION
Snap points to their nearest line
.SH USAGE
geoc vector snap points2lines -i points.shp -k lines.shp -o snapped.shp -d 2
.SH OPTIONS
-d --search-distance: The distance to search for the closest line
.PP
-s --snapped-fieldname: The name for the snapped Field
.PP
-k --other-workspace: The other workspace
.PP
-y --other-layer: The other layer
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
