.TH "geoc-tile-vector-grid" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc tile vector grid
.SH DESCRIPTION
Create a vector grid of a tile layers cells.
.SH USAGE
geoc tile vector grid -l earthquakes.mbtiles -z 1 -o grid.shp
.SH OPTIONS
-l --tile-layer: The tile layer
.PP
-b --bounds: The bounds
.PP
-z --zoom-level: The tile zoom level
.PP
-x --minx: The min x or col
.PP
-y --miny: The min y or row
.PP
-c --maxx: The max x or col
.PP
-u --maxy: The max y or row
.PP
-w --width: The raster width
.PP
-h --height: The raster height
.PP
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
