.TH "geoc-raster-multiply" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc raster multiply
.SH DESCRIPTION
Multiply two Rasters together
.SH OPTIONS
-k --other-raster: The other raster
.PP
-j --other-projection: The other projection
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
