.TH "geoc-vector-heatmap" "1" "20 December 2014" "version 0.1"
.SH NAME
geoc vector heatmap
.SH DESCRIPTION
Create a heatmap of the input layer
.SH USAGE
geoc vector heatmap -i earthquakes.properties -o heatmap.tif -r 50 -w 800 -h 800
.SH OPTIONS
-r --radius-pixels: The radius of the density kernel in pixels
.PP
-a --weight-field: The name of the weight field
.PP
-p --pixels-per-cell: The resolution of the computed grid
.PP
-b --bounds: The output bounds
.PP
-w --width: The output width
.PP
-h --height: The output height
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
--help : Print the help message
.PP
