.TH "geoc-raster-mapalgebra" "1" "22 December 2014" "version 0.1"
.SH NAME
geoc raster mapalgebra
.SH DESCRIPTION
Perform map algebra
.SH USAGE
geoc raster mapalgebra -s "dest = r1 * r2" -r "r1=raster1.acs" -r "r2=raster2.acs" -o raster_add.tif -p "EPSG:4326"
.SH OPTIONS
-s --script: The map algebra (jiffle) script
.PP
-r --raster: An input Raster
.PP
-b --bounds: The bounds
.PP
-z --size: The size
.PP
-n --output-name: The output name
.PP
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-p --output-raster-projection: The output raster projection
.PP
--help : Print the help message
.PP
