.TH "geoc-vector-uniquevaluesstyle" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc vector uniquevaluesstyle
.SH DESCRIPTION
Create an SLD document where each unique value in the Layer is a rule.
.SH OPTIONS
-f --field: The field name
.PP
-c --colors: The color brewer palette name or a list of colors (space delimited)
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
