.TH "geoc-raster-invert" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc raster invert
.SH DESCRIPTION
Invert the values of a Raster
.SH OPTIONS
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-l --input-raster-name: The input raster name
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
