.TH "geoc-vector-geomw" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector geomw
.SH DESCRIPTION
Convert the input layer to a text stream of WKT geometries that can be read by the geom commands
.SH OPTIONS
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
