.TH "geoc-vector-gradientstyle" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector gradientstyle
.SH DESCRIPTION
Create a gradient SLD for the Layer.
.SH OPTIONS
-f --field: The field name
.PP
-n --number: The number of categories
.PP
-c --colors: The color brewer palette name or a list of colors (space delimited)
.PP
-m --method: The classification method (Quantile or EqualInterval)
.PP
-e --else-mode: The else mode (ignore, min, max)
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
