.TH "geoc-geometry-offset" "1" "22 October 2015" "version 0.1"
.SH NAME
geoc geometry offset
.SH DESCRIPTION
Create a Geometry offset from the input Geometry
.SH USAGE
geoc geometry offset -i "LINESTRING (10 0, 10 10)" -d 5 -s 8
.SH OPTIONS
-i --input: The input geometry
.PP
-d --offset: The offset distance
.PP
-s --quadrant-segements: The number of quadrant segments (defaults to 8)
.PP
--help : Print the help message
.PP
