.TH "geoc-vector-envelopes" "1" "29 July 2014" "version 0.1"
.SH NAME
geoc vector envelopes
.SH DESCRIPTION
Calculate the envelope of each feature in the input Layer and save them to the output Layer
.SH OPTIONS
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
