.TH "geoc-vector-splitbylayer" "1" "11 September 2016" "version 0.1"
.SH NAME
geoc vector splitbylayer
.SH DESCRIPTION
Split a Layer into separate Layers based on the Feature from another Layer
.SH USAGE
geoc vector splitbylayer -i states.shp -s states_grid.shp -o statesgrid -f col_row
.SH OPTIONS
-s --split-workspace: The input workspace
.PP
-p --split-layer: The input layer
.PP
-f --field: The field name
.PP
-o --output-workspace: The output workspace
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
