.TH "geoc-vector-info" "1" "12 December 2014" "version 0.1"
.SH NAME
geoc vector info
.SH DESCRIPTION
Get basic information about the Layer
.SH USAGE
geoc vector info -i zones.shp
.SH OPTIONS
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
