.TH "geoc-vector-voronoi" "1" "9 December 2014" "version 0.1"
.SH NAME
geoc vector voronoi
.SH DESCRIPTION
Calculate a voronoi diagram of the input Layer and save it to the output Layer
.SH USAGE
geoc vector voronoi -i states.shp -o states_voronoi.shp
.SH OPTIONS
-o --output-workspace: The output workspace
.PP
-r --output-layer: The output layer
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
