.TH "geoc-style-repository-copy" "1" "19 October 2021" "version 0.1"
.SH NAME
geoc style repository copy
.SH DESCRIPTION
Copy styles from one repository to another
.SH OPTIONS
-t --input-type: The type of style repository (directory, nested-directory, h2, sqlite, postgres)
.PP
-p --input-options: The style repository options
.PP
-o --output-type: The type of style repository (directory, nested-directory, h2, sqlite, postgres)
.PP
-r --output-options: The style repository options
.PP
--help : Print the help message
.PP
--web-help : Open help in a browser
.PP
