.TH "geoc-vector-splitbyfield" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc vector splitbyfield
.SH DESCRIPTION
Split a Layer into separate Layers based on values from a Field
.SH OPTIONS
-f --field: The field name
.PP
-o --output-workspace: The output workspace
.PP
-i --input-workspace: The input workspace
.PP
-l --input-layer: The input layer
.PP
--help : Print the help message
.PP
