.TH "geoc-raster-to" "1" "5 May 2013" "version 0.1"
.SH NAME
geoc raster to
.SH DESCRIPTION
Convert a Raster from one format to another
.SH OPTIONS
-o --output-raster: The output raster
.PP
-f --output-raster-format: The output raster format
.PP
-i --input-raster: The input raster
.PP
-p --input-projection: The input projection
.PP
--help : Print the help message
.PP
