#!/bin/bash
./filter_cql2xml.sh
./geom_convert.sh
./geom_decimaldegrees.sh
./geom_distance.sh
./geom_geohash.sh
./geom_greatcircle.sh
./geom_offset.sh
./geom_plot.sh
./geopackage.sh
./list_commands.sh
./man_pages.sh
./map_cube.sh
./map_cube_watercolor.sh
./map_osm.sh
./map_osm_toner.sh
./map_osm_toner_lite.sh
./map_osm_watercolor.sh
./proj_wkt_env.sh
./raster_display.sh
./raster_draw.sh
./raster_info.sh
./raster_crop.sh
./raster_srtm.sh
./style_ysld.sh
./tile_geopackage.sh
./tile_mbtiles.sh
./tile_mvt.sh
./tile_tms.sh
./tile_vector_grid.sh
./vector_buffer.sh
./vector_centroid.sh
./vector_copy.sh
./vector_convexhull.sh
./vector_datasources.sh
./vector_delaunay.sh
./vector_display.sh
./vector_draw.sh
./vector_envelope.sh
./vector_fields.sh
./vector_geomr.sh
./vector_gradientstyle.sh
./vector_interiorpoint.sh
./vector_metadata.sh
./vector_mincircle.sh
./vector_minrect.sh
./vector_octagonalenvelope.sh
./vector_random.sh
./vector_supercircle.sh
./vector_uniquevaluesstyle.sh
./vector_voronoi.sh
