name: Maven Package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github-geoc
    - name: Publish
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ github.GITHUB_TOKEN }}
